ignore:
  - "backend/cmd/main.go"
  - "backend/internal/db/*"
  - "backend/schema.sql"
  - "backend/go.mod"
  - "backend/go.sum"
  - "coverage.out"
  - ".github/workflows/*"
  - "frontend/*"
  - "*.md"
  - "LICENSE"
  - ".gitignore"