// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bookings.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createBooking = `-- name: CreateBooking :exec
INSERT INTO bookings (id, created_at, updated_at, appointment_start, duration_minutes, user_id)
VALUES (
    uuid(),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    ?,
    ?,
    ?
)
`

type CreateBookingParams struct {
	AppointmentStart time.Time
	DurationMinutes  int64
	UserID           interface{}
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) error {
	_, err := q.db.ExecContext(ctx, createBooking, arg.AppointmentStart, arg.DurationMinutes, arg.UserID)
	return err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings 
WHERE id = ? AND user_id = ?
`

type DeleteBookingParams struct {
	ID     interface{}
	UserID interface{}
}

func (q *Queries) DeleteBooking(ctx context.Context, arg DeleteBookingParams) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, arg.ID, arg.UserID)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, created_at, updated_at, appointment_start, duration_minutes, user_id FROM bookings
WHERE id = ?
`

func (q *Queries) GetBookingByID(ctx context.Context, id interface{}) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AppointmentStart,
		&i.DurationMinutes,
		&i.UserID,
	)
	return i, err
}

const getOverlappingBookings = `-- name: GetOverlappingBookings :many
SELECT id, created_at, updated_at, appointment_start, duration_minutes, user_id FROM bookings
WHERE appointment_start < DATETIME(?, '+' || ? || ' minutes')
AND DATETIME(appointment_start, '+' || duration_minutes || ' minutes') > ?
`

type GetOverlappingBookingsParams struct {
	Datetime         interface{}
	Column2          sql.NullString
	AppointmentStart time.Time
}

func (q *Queries) GetOverlappingBookings(ctx context.Context, arg GetOverlappingBookingsParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, getOverlappingBookings, arg.Datetime, arg.Column2, arg.AppointmentStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentStart,
			&i.DurationMinutes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBookingsForAdmin = `-- name: ListAllBookingsForAdmin :many
SELECT id, created_at, updated_at, appointment_start, duration_minutes, user_id From bookings
ORDER BY appointment_start
`

func (q *Queries) ListAllBookingsForAdmin(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listAllBookingsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentStart,
			&i.DurationMinutes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsForUser = `-- name: ListBookingsForUser :many
SELECT id, created_at, updated_at, appointment_start, duration_minutes, user_id FROM bookings
WHERE user_id = ?
ORDER BY appointment_start
`

func (q *Queries) ListBookingsForUser(ctx context.Context, userID interface{}) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppointmentStart,
			&i.DurationMinutes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
