// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Admin struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}

type Booking struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	AppointmentStart time.Time
	DurationMinutes  int64
	UserID           uuid.UUID
}

type User struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}
