// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Admin struct {
	ID           interface{}
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}

type Booking struct {
	ID               interface{}
	CreatedAt        time.Time
	UpdatedAt        time.Time
	AppointmentStart time.Time
	DurationMinutes  int64
	UserID           interface{}
}

type User struct {
	ID           interface{}
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}
